#!/usr/local/bin/php
<?php
/**
 * @internal this is all devel level code just for testing out on other systems
 */

require_once dirname(__FILE__) . '/../src/PHPT/Framework.php';

$controller = new PHPT_Controller_CLI();
$controller->run($argv);
